[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"  # Use a newer Solidity version
optimizer = true
optimizer_runs = 200
evm_version = "paris"  # Specify EVM version (post-Merge)
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# RPC endpoints for deployment
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"  # For Anvil

# Etherscan API keys for contract verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }

# Testing configuration
[profile.test]
src = "test"
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

# Formatting (optional)
[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
